// Generated by CoffeeScript 2.3.2
(function() {
  $(function() {
    window.v = new Vue({
      el: '#工程信息',
      data: {
        標題: '',
        主解析度: '',
        工程路徑: ''
      }
    });
    $("#開啓工程").click(function() {
      return send("開啓工程");
    });
    $("#建立工程").click(function() {
      return send("建立工程");
    });
    $("#運行").click(function() {
      return send("運行");
    });
    $("#運行同時編寫").click(function() {
      return send("運行同時編寫");
    });
    $("#打開文件夾").click(function() {
      return send("打開文件夾");
    });
    $("#生成exe").click(function() {
      return send("生成exe");
    });
    $("#生成html").click(function() {
      return send("生成html");
    });
    return window.進入工程 = function() {
      return $("#入口").slideUp();
    };
  });

}).call(this);
