// Generated by CoffeeScript 2.3.2
(function() {
  $(function() {
    var 響應表;
    window.v = new Vue({
      el: '#all',
      data: {
        標題: '',
        主解析度: '',
        工程路徑: '',
        圖標路徑: '',
        存檔資料: []
      },
      watch: {
        $data: {
          handler: function(val, oldVal) {
            return 山彥.vue更新(val);
          },
          deep: true
        }
      }
    });
    山彥.vue連接初始化(function(x) {
      var a, b, results;
      results = [];
      for (a in x) {
        b = x[a];
        results.push(v[a] = b);
      }
      return results;
    });
    響應表 = {
      開啓工程: function() {
        return 山彥.開啓工程();
      },
      建立工程: function() {
        return 山彥.建立工程();
      },
      清除記錄: function() {
        return v.存檔資料 = [];
      },
      運行: function() {
        return 山彥.運行();
      },
      運行同時編寫: function() {
        return 山彥.運行同時編寫();
      },
      打開文件夾: function() {
        return 山彥.打開文件夾();
      },
      生成exe: function() {
        return 山彥.生成exe();
      },
      返回: function() {
        return window.返回();
      }
    };
    $('body').on('click', 'a', function(event) {
      var id;
      id = $(this).attr('id');
      if (id) {
        return 響應表[id]();
      } else {
        return console.log('沒有可響應的id');
      }
    });
    window.進入工程 = function() {
      $('.頁').hide();
      return $('#工程編輯').show();
    };
    window.返回 = function() {
      $('.頁').hide();
      return $('#入口').show();
    };
    return window.返回();
  });

}).call(this);
