// Generated by CoffeeScript 2.3.2
(function() {
  window.控制 = {
    右鍵功能: function() {
      window.event.returnValue = false;
      $('#對話框').fadeToggle(250);
      return $('.scroll').fadeOut(200);
    },
    左鍵屏蔽: false,
    左鍵功能: function() {
      if (this.左鍵屏蔽 || 演出.選擇之刻) {
        return;
      }
      if ($('#對話框').is(':hidden')) {
        $('.scroll').fadeOut(200);
        return $('#對話框').fadeIn(250);
      } else {
        if (Date.now() < 演出.淡入過期時間) {
          演出.淡入過期時間 = 0;
          return 演出.早泄();
        } else {
          return 演出.步進更新();
        }
      }
    },
    顯示履歷: function() {
      if (!($('.scroll').is(':hidden'))) {
        return;
      }
      $('#對話框').fadeOut(200);
      $('.scroll').show(0);
      return $('.scroll').animate({
        scrollTop: 99999999
      }, 0);
    },
    正在快進: false,
    開始快進: function() {
      if (this.正在快進 === false) {
        this.正在快進 = true;
        return this.快進輪迴();
      }
    },
    結束快進: function() {
      return this.正在快進 = false;
    },
    切換快進: function() {
      if (this.正在快進 === false) {
        this.正在快進 = true;
        return this.快進輪迴();
      } else {
        return this.正在快進 = false;
      }
    },
    快進輪迴: function() {
      if (控制.正在快進 === false) {

      } else {
        控制.左鍵功能();
        return setTimeout(控制.快進輪迴, 75);
      }
    },
    進入設置: function() {
      return $('#配置面板').fadeIn(300);
    },
    退出設置: function() {
      return $('#配置面板').fadeOut(300);
    }
  };

  window.document.onkeydown = function(evt) {
    var k;
    k = evt.keyCode;
    // [ctrl] skip
    if (k === 17) {
      console.log('ctrl按下');
      控制.開始快進();
    }
    // [空格 回車 z] 左鍵
    if (k === 32 || k === 13 || k === 90) {
      控制.左鍵功能();
    }
    // [esc] 右鍵
    if (k === 27) {
      控制.右鍵功能();
    }
    // [Page_up] 歷史
    if (k === 33) {
      return 控制.顯示履歷();
    }
  };

  window.document.onkeyup = function(evt) {
    // [ctrl] skip
    if (evt.keyCode === 17) {
      console.log('ctrl放開');
      return 控制.結束快進();
    }
  };

  // 滚轮功能
  $(function() {
    $('#主畫面').mousewheel(function(event, delta) {
      if (delta > 0) {
        控制.顯示履歷();
      }
      if (delta < 0) {
        if ($('.scroll').is(':hidden')) {
          return 控制.左鍵功能();
        }
      }
    });
    $("#主畫面").mousedown(function(e) {
      if (e.which === 3) {
        return 控制.右鍵功能();
      } else if (e.which === 1) {
        console.log(16);
        return 控制.左鍵功能();
      }
    });
    return $("#覆蓋").mousedown(function(e) {
      if (e.which === 1) {
        console.log(32);
        $("#覆蓋").hide();
        return 演出.步進更新();
      }
    });
  });

}).call(this);
