// Generated by CoffeeScript 2.3.2
(function() {
  window.演出 = {
    準備工作: function() {
      $("<link>").attr({
        rel: "stylesheet",
        type: "text/css",
        href: this.自定css
      }).appendTo("head");
      $("<link>").attr({
        rel: "stylesheet",
        type: "text/css",
        href: this.主題css
      }).appendTo("head");
      $('#總畫面').css('width', 解析度[0]);
      $('#總畫面').css('height', 解析度[1]);
      if (邊界) {
        $('div').css('border', '1px solid #22f');
      }
      this.換圖('覆蓋', 'url(static/None.png)', 0);
      this.換圖('bg', 'url(static/None.png)', 0);
      this.換圖('cg', 'url(static/None.png)', 0);
      return this.更新();
    },
    步進更新: function() {
      return send('步進更新');
    },
    更新: function() {
      return send('更新');
    },
    信息預處理: function(data) {
      if (!data.bg) {
        data.bg = 'url(static/None.png)';
      } else {
        data.bg = `url(${this.圖片文件夾}/${data.bg})`;
      }
      if (!data.cg) {
        data.cg = 'url(static/None.png)';
      } else {
        data.bg = `url(${this.圖片文件夾}/${data.cg})`;
      }
      if (data.bgm[0] !== 'None') {
        data.bgm[0] = this.音樂文件夾 + '/' + data.bgm[0];
      }
      if (data.name !== '') {
        data.word = `「${data.word}」`;
        return $('#名字框').fadeIn(200);
      } else {
        data.word = '　　' + data.word;
        return $('#名字框').fadeOut(200);
      }
    },
    改變演出狀態: function(data) {
      var bg, bgm, cg, ch, choice, info, name, word, 特效表;
      this.信息預處理(data);
      ({bg, bgm, cg, 特效表, ch, choice, name, word, info} = data);
      this.特效處理(特效表);
      if (choice.length > 0) {
        this.處理選項(choice);
        return;
      }
      if (info) {
        if (info[0] === 'cut') {
          name = '';
          word = '';
          bgm = ['None', 0];
          this.插入圖(info[1]);
        }
        if (info[0] === 'video') {
          this.放視頻(info[1]);
        }
        if (info[0] === 'load') {
          this.load特效();
        }
      }
      this.換cg(cg);
      this.換bg(bg);
      this.換立繪(ch);
      this.換bgm(bgm);
      this.換人名(name);
      return this.換對話(word, name);
    },
    特效處理: function(特效表) {
      var i, j, k, len, len1, results, 可特效块;
      可特效块 = ['總畫面', 'adv畫面', '覆蓋', '選項', 'cg', 'bg', '立繪', '對話歷史', '對話框', '名字框', '名字', '名字框背景', '話語框', '話語', '話語框背景', '對話框背景'];
      for (j = 0, len = 可特效块.length; j < len; j++) {
        i = 可特效块[j];
        if ($('#' + i).attr('class')) {
          $('#' + i).attr('class', '');
        }
      }
      results = [];
      for (k = 0, len1 = 特效表.length; k < len1; k++) {
        i = 特效表[k];
        results.push($('#' + i).addClass(特效表[i]));
      }
      return results;
    },
    選擇之刻: false,
    處理選項: function(choice) {
      var i, j, len, tot;
      tot = '';
      for (j = 0, len = choice.length; j < len; j++) {
        i = choice[j];
        tot += `<button onclick='this.點選項(${i});'>${choice[i]}</botton>\n`;
      }
      $('#選項').html(tot);
      $('#選項').show(250);
      return this.選擇之刻 = true;
    },
    點選項: function(x) {
      $('#選項').hide(250);
      send('選', x + '');
      return this.選擇之刻 = false;
    },
    插入圖: function(圖) {
      控制.左鍵屏蔽 = true;
      $('#覆蓋').css('display', 'block');
      $('#總畫面').fadeOut(1400);
      setTimeout(function() {
        return 演出.換圖('覆蓋', 'url(' + 演出.圖片文件夾 + '/' + 圖 + ')', 0);
      }, 1500);
      setTimeout(function() {
        return 演出.步進更新();
      }, 1500);
      setTimeout(function() {
        return $('#總畫面').fadeIn(1100);
      }, 1500);
      setTimeout(function() {
        return 演出.換圖('覆蓋', 'url(static/None.png)', 1);
      }, 4500);
      setTimeout(function() {
        return $('#覆蓋').css('animation', '');
      }, 5550);
      setTimeout(function() {
        return $('#覆蓋').css('display', 'none');
      }, 5600);
      return setTimeout(function() {
        return 控制.左鍵屏蔽 = false;
      }, 5600);
    },
    放視頻: function(視頻) {
      var v;
      控制.左鍵屏蔽 = true;
      v = $('video');
      v.css('display', 'block');
      v.attr('src', this.視頻文件夾 + '/' + 視頻);
      v[0].addEventListener('ended', function() {
        this.步進更新();
        return setTimeout(function() {
          v[0].style.display = 'none';
          return 控制.左鍵屏蔽 = false;
        }, 500);
      }, false);
      return v[0].play();
    },
    load特效: function() {
      控制.左鍵屏蔽 = true;
      $('#總畫面').fadeOut(0);
      $('#總畫面').fadeIn(1200);
      return setTimeout(function() {
        return 控制.左鍵屏蔽 = false;
      }, 1000);
    },
    提示: function(x) {
      $('#提示').html(x);
      $('#提示').fadeIn(300);
      return $('#提示').hide(1000);
    },
    現在cg: 'None',
    換cg: function(cg) {
      if (cg === this.現在cg) {
        return;
      }
      this.現在cg = cg;
      return this.換圖('cg', cg, 1);
    },
    換立繪: function(text) {
      return $('#立繪').html(text);
    },
    現在bg: 'None',
    換bg: function(bg) {
      var 現在bg;
      if (bg === this.現在bg) {
        return;
      }
      現在bg = bg;
      if (bg === 'None') {
        bg = 'url(static/None.png)';
      }
      return this.換圖('bg', bg, 1.4);
    },
    換人名: function(text) {
      $('#名字').html(text);
      return $('#對話歷史').append(text + '<br/>');
    },
    換對話: function(text, name) {
      if (name) {
        $('#話語').逐字打印(text, true);
      } else {
        $('#話語').逐字打印(text);
      }
      return $('#對話歷史').append(text + '<br/><br/>');
    },
    當前曲名: 'None',
    換bgm: function(bgm) {
      var au, 曲名, 音量;
      曲名 = bgm[0];
      音量 = bgm[1];
      au = $('#bgm');
      if (this.當前曲名 === 曲名) {
        return;
      }
      this.當前曲名 = 曲名;
      if (this.當前曲名 === 'None') {
        au.stop();
        au.animate({
          volume: 0
        }, 2000);
        return setTimeout(function() {
          return au.attr('src', 演出.當前曲名);
        }, 2000);
      } else {
        au.stop();
        au.attr('src', this.當前曲名);
        au.animate({
          volume: 0
        }, 0);
        return au.animate({
          volume: 音量
        }, 2000);
      }
    },
    換圖: function(dst, img_b, time) {
      var frame, img_a;
      frame = 'A' + Math.ceil(Math.random() * 999999).toString();
      dst = '#' + dst;
      img_a = $(dst).attr('my_img');
      if (time > 0) {
        $(dst).css('animation', '');
        $('#style').append('@keyframes ' + frame + '{ 0%{background-image:' + img_a + ';}100%{background-image:' + img_b + ';} }\n');
        $(dst).css('animation', frame + ' ' + time.toString() + 's');
      }
      $(dst).css('background-image', img_b);
      return $(dst).attr('my_img', img_b);
    }
  };

}).call(this);
