// Generated by CoffeeScript 2.3.2
(function() {
  var 在線運行, 本地運行;

  $(function() {
    if (window.山彥) {
      console.log('在本地演出');
      return 本地運行();
    } else {
      console.log('在瀏覽器上演出');
      return 在線運行();
    }
  });

  本地運行 = function() {
    window.v = new Vue({
      el: '#總畫面',
      data: {
        圖片文件夾: '',
        音樂文件夾: '',
        視頻文件夾: '',
        臨時立繪文件夾: '',
        自定css: '',
        主題css: '',
        解析度: '',
        邊界: '',
        用戶設置: {
          文字速度: 35,
          對話框背景透明度: 0.8,
          自動收起控制面板: true,
          總體音量: 1
        }
      },
      watch: {
        $data: {
          handler: function(val, oldVal) {
            return 山彥.vue更新(val);
          },
          deep: true
        }
      }
    });
    山彥.vue連接初始化(function(x) {
      var a, b, results;
      results = [];
      for (a in x) {
        b = x[a];
        results.push(v[a] = b);
      }
      return results;
    });
    return 山彥.初始化();
  };

  在線運行 = function() {
    if (typeof 虛擬核心 === "undefined") {
      alert('無法加載虛擬核心。');
      return;
    }
    window.山彥 = {
      n: 0,
      更新: function() {
        return 演出.改變演出狀態(虛擬核心.演出步[this.n]);
      },
      步進: function() {
        return this.n += 1;
      },
      步進更新: function() {
        this.步進();
        return this.更新();
      },
      設置: function() {
        return 0;
      },
      初始化: function() {
        return 演出.準備工作();
      }
    };
    window.v = new Vue({
      el: '#總畫面',
      data: {
        圖片文件夾: 虛擬核心.圖片文件夾,
        音樂文件夾: 虛擬核心.音樂文件夾,
        視頻文件夾: 虛擬核心.視頻文件夾,
        臨時立繪文件夾: 虛擬核心.臨時立繪文件夾,
        自定css: 虛擬核心.自定css,
        主題css: 虛擬核心.主題css,
        解析度: 虛擬核心.解析度,
        邊界: 虛擬核心.邊界,
        用戶設置: {
          文字速度: 35,
          對話框背景透明度: 0.8,
          自動收起控制面板: true,
          總體音量: 1
        }
      }
    });
    $('title').html(虛擬核心.作品名);
    return 山彥.初始化();
  };

}).call(this);
