// Generated by CoffeeScript 2.3.2
(function() {
  var 在線運行, 從虛擬核心提取資源, 本地運行;

  $(function() {
    if (window.山彥) {
      window.本地 = console.log('在本地演出');
      return 本地運行();
    } else {
      console.log('在瀏覽器上演出');
      return 在線運行();
    }
  });

  本地運行 = function() {
    window.v = new Vue({
      el: '#總畫面',
      data: {
        圖片文件夾: '',
        音樂文件夾: '',
        視頻文件夾: '',
        臨時立繪文件夾: '',
        自定css: '',
        主題css: '',
        解析度: '',
        邊界: '',
        用戶設置: {
          文字速度: 35,
          對話框背景透明度: 0.8,
          自動收起控制面板: true,
          總體音量: 1
        }
      },
      watch: {
        $data: {
          handler: function(val, oldVal) {
            return 山彥.vue更新(val);
          },
          deep: true
        }
      }
    });
    山彥.vue連接初始化(function(x) {
      var a, b, results;
      results = [];
      for (a in x) {
        b = x[a];
        results.push(v[a] = b);
      }
      return results;
    });
    return 山彥.初始化();
  };

  從虛擬核心提取資源 = function(心) {
    var data, i, j, k, l, len, len1, len2, ref, ref1, 人, 圖層, 步, 集合;
    集合 = {};
    步 = JSON.parse(JSON.stringify(心.演出步));
    for (j = 0, len = 步.length; j < len; j++) {
      data = 步[j];
      if (data.背景) {
        集合[`${v.圖片文件夾}/${data.背景[0]}`] = true;
      }
      if (data.cg) {
        集合[`${v.圖片文件夾}/${data.cg[0]}`] = true;
      }
      if (data.背景音樂[0] !== 'None') {
        集合[v.音樂文件夾 + '/' + data.背景音樂[0]] = true;
      }
      ref = data.立繪;
      for (k = 0, len1 = ref.length; k < len1; k++) {
        人 = ref[k];
        ref1 = 人.圖層;
        for (l = 0, len2 = ref1.length; l < len2; l++) {
          圖層 = ref1[l];
          集合[`${v.臨時立繪文件夾}/${圖層.文件}`] = true;
        }
      }
    }
    return (function() {
      var results;
      results = [];
      for (i in 集合) {
        results.push(i);
      }
      return results;
    })();
  };

  window.加載完成的初始化 = function() {
    $('#加載畫面').fadeOut();
    return 山彥.初始化();
  };

  在線運行 = function() {
    var j, len, 資源, 資源組;
    if (typeof 虛擬核心 === "undefined") {
      alert('無法加載虛擬核心。');
      return;
    }
    $('#加載畫面').css('display', 'flex');
    window.山彥 = {
      n: 0,
      更新: function() {
        return 演出.改變演出狀態(虛擬核心.演出步[this.n]);
      },
      步進: function() {
        return this.n += 1;
      },
      步進更新: function() {
        this.步進();
        return this.更新();
      },
      設置: function() {
        return 0;
      },
      初始化: function() {
        return 演出.準備工作();
      }
    };
    window.v = new Vue({
      el: '#總畫面',
      data: {
        圖片文件夾: 虛擬核心.圖片文件夾,
        音樂文件夾: 虛擬核心.音樂文件夾,
        視頻文件夾: 虛擬核心.視頻文件夾,
        臨時立繪文件夾: 虛擬核心.臨時立繪文件夾,
        自定css: 虛擬核心.自定css,
        主題css: 虛擬核心.主題css,
        解析度: 虛擬核心.解析度,
        邊界: 虛擬核心.邊界,
        用戶設置: {
          文字速度: 35,
          對話框背景透明度: 0.8,
          自動收起控制面板: true,
          總體音量: 1
        }
      }
    });
    資源組 = 從虛擬核心提取資源(虛擬核心);
    window.v加載 = new Vue({
      el: '#加載畫面',
      data: {
        最大值: 資源組.length,
        計數: 0
      }
    });
    for (j = 0, len = 資源組.length; j < len; j++) {
      資源 = 資源組[j];
      $.get(資源, function() {
        return v加載.計數 += 1;
      });
    }
    return $('title').html(虛擬核心.作品名);
  };

}).call(this);
