name: CI

on:
  push:
  pull_request:

jobs:
  test-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8.18', '3.10.21', '3.12.14', '3.14.7']
    steps: &steps
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install .
  test-install-36:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ['3.6.15']
    steps: *steps
